// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_Server_Application_Final_Project.Models;

#nullable disable

namespace Web_Server_Application_Final_Project.Migrations
{
    [DbContext(typeof(FinalContext))]
    [Migration("20241204002342_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Web_Server_Application_Final_Project.Models.Camera", b =>
                {
                    b.Property<int>("CameraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CameraId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Rating")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Sensor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Year")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("CameraId");

                    b.ToTable("Cameras");

                    b.HasData(
                        new
                        {
                            CameraId = 1,
                            Description = "A mirrorless-type camera. My most recent camera.",
                            Name = "Nikon Z6",
                            Rating = 1,
                            Sensor = "24.5MP Full Frame",
                            Year = 2018
                        },
                        new
                        {
                            CameraId = 2,
                            Description = "A mirrorless-type camera. I have tested a few times.",
                            Name = "Nikon Z9",
                            Rating = 2,
                            Sensor = "45.7MP Full Frame",
                            Year = 2021
                        },
                        new
                        {
                            CameraId = 3,
                            Description = "A DSLR-type camera. My second camera.",
                            Name = "Nikon d5500",
                            Rating = 3,
                            Sensor = "24.2MP Crop Size",
                            Year = 2015
                        },
                        new
                        {
                            CameraId = 4,
                            Description = "A DSLR-type camera. My first camera.",
                            Name = "Nikon d3000",
                            Rating = 4,
                            Sensor = "10.2MP Crop Size",
                            Year = 2007
                        });
                });

            modelBuilder.Entity("Web_Server_Application_Final_Project.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Rating")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("TypesId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Year")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("GameId");

                    b.HasIndex("TypesId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            Name = "Medal of Honor Frontline",
                            Rating = 5,
                            TypesId = "S",
                            Year = 2002
                        },
                        new
                        {
                            GameId = 2,
                            Name = "Far Cry 6",
                            Rating = 5,
                            TypesId = "F",
                            Year = 2021
                        },
                        new
                        {
                            GameId = 3,
                            Name = "Call of Duty Black Ops 2",
                            Rating = 5,
                            TypesId = "S",
                            Year = 2012
                        },
                        new
                        {
                            GameId = 4,
                            Name = "HellDivers 2",
                            Rating = 4,
                            TypesId = "T",
                            Year = 2024
                        },
                        new
                        {
                            GameId = 5,
                            Name = "God of War",
                            Rating = 5,
                            TypesId = "R",
                            Year = 2018
                        },
                        new
                        {
                            GameId = 6,
                            Name = "Infamous",
                            Rating = 4,
                            TypesId = "T",
                            Year = 2010
                        },
                        new
                        {
                            GameId = 7,
                            Name = "The Last of Us",
                            Rating = 4,
                            TypesId = "R",
                            Year = 2014
                        });
                });

            modelBuilder.Entity("Web_Server_Application_Final_Project.Models.Genre", b =>
                {
                    b.Property<string>("GenreId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreId = "A",
                            Name = "Action"
                        },
                        new
                        {
                            GenreId = "C",
                            Name = "Comedy"
                        },
                        new
                        {
                            GenreId = "D",
                            Name = "Drama"
                        },
                        new
                        {
                            GenreId = "H",
                            Name = "Horror"
                        },
                        new
                        {
                            GenreId = "M",
                            Name = "Musical"
                        },
                        new
                        {
                            GenreId = "R",
                            Name = "RomCom"
                        },
                        new
                        {
                            GenreId = "S",
                            Name = "SciFi"
                        });
                });

            modelBuilder.Entity("Web_Server_Application_Final_Project.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descriptor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Rating")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Year")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            Description = "The highest peak in the Great Smoky Mountains, offering breathtaking panoramic views.",
                            Descriptor = "Bryson City, North Carolina",
                            Name = "Clingmans Dome",
                            Rating = 1,
                            Year = 1959
                        },
                        new
                        {
                            LocationId = 2,
                            Description = "A charming town in Tennessee nestled in the Smoky Mountains, renowned for its attractions, shopping, and natural beauty.",
                            Descriptor = "Gatlinburg, Tennessee",
                            Name = "Gatlinburg",
                            Rating = 2,
                            Year = 1854
                        },
                        new
                        {
                            LocationId = 3,
                            Description = "One of the world's most famous natural wonders, with its powerful and majestic waterfalls.",
                            Descriptor = "Niagara Falls,New York",
                            Name = "Niagara Falls",
                            Rating = 3,
                            Year = 1678
                        },
                        new
                        {
                            LocationId = 4,
                            Description = "This Ohio state park is renowned for its stunning natural features including cliffs, waterfalls, and lush forest trails.",
                            Descriptor = "Logan, Ohio",
                            Name = "Hocking Hills State Park",
                            Rating = 4,
                            Year = 1924
                        },
                        new
                        {
                            LocationId = 5,
                            Description = "Indiana's largest state park, known for its rolling hills, scenic vistas, and vibrant fall foliage.",
                            Descriptor = "Nashville, Indiana",
                            Name = "Brown County State Park",
                            Rating = 5,
                            Year = 1929
                        },
                        new
                        {
                            LocationId = 6,
                            Description = "This museum showcases an extensive collection of historic aircraft and aviation artifacts.",
                            Descriptor = "Dayton, Ohio",
                            Name = "Museum of the Air Force",
                            Rating = 6,
                            Year = 1923
                        },
                        new
                        {
                            LocationId = 7,
                            Description = "A historic cemetery and arboretum celebrated for its beautiful landscapes and monuments.",
                            Descriptor = "Cincinnati, Ohio",
                            Name = "Spring Grove",
                            Rating = 7,
                            Year = 1845
                        },
                        new
                        {
                            LocationId = 8,
                            Description = "A popular destination for boating, fishing, and camping, surrounded by lush forests.",
                            Descriptor = "Brookville, Indiana",
                            Name = "Brookville Lake",
                            Rating = 8,
                            Year = 1974
                        },
                        new
                        {
                            LocationId = 9,
                            Description = "This park offers picturesque hiking trails, fishing, and recreational activities.",
                            Descriptor = "Harrison, Ohio",
                            Name = "Miami Whitewater Forest",
                            Rating = 9,
                            Year = 1949
                        });
                });

            modelBuilder.Entity("Web_Server_Application_Final_Project.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"));

                    b.Property<string>("GenreId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Rating")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Year")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("MovieId");

                    b.HasIndex("GenreId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            GenreId = "A",
                            Name = "Kingsman",
                            Rating = 5,
                            Year = 2012
                        },
                        new
                        {
                            MovieId = 2,
                            GenreId = "A",
                            Name = "Batman Begins",
                            Rating = 5,
                            Year = 2005
                        },
                        new
                        {
                            MovieId = 3,
                            GenreId = "M",
                            Name = "The Sound of Music",
                            Rating = 5,
                            Year = 1965
                        },
                        new
                        {
                            MovieId = 4,
                            GenreId = "D",
                            Name = "Hacksaw Ridge",
                            Rating = 5,
                            Year = 2016
                        },
                        new
                        {
                            MovieId = 5,
                            GenreId = "S",
                            Name = "Back to the Future 2",
                            Rating = 3,
                            Year = 1989
                        },
                        new
                        {
                            MovieId = 6,
                            GenreId = "R",
                            Name = "DeadPool and Wolverine",
                            Rating = 5,
                            Year = 2024
                        },
                        new
                        {
                            MovieId = 7,
                            GenreId = "H",
                            Name = "Saw",
                            Rating = 5,
                            Year = 2004
                        });
                });

            modelBuilder.Entity("Web_Server_Application_Final_Project.Models.Types", b =>
                {
                    b.Property<string>("TypesId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypesId");

                    b.ToTable("Types");

                    b.HasData(
                        new
                        {
                            TypesId = "F",
                            Name = "First Person"
                        },
                        new
                        {
                            TypesId = "M",
                            Name = "MMO"
                        },
                        new
                        {
                            TypesId = "T",
                            Name = "Third Person"
                        },
                        new
                        {
                            TypesId = "S",
                            Name = "Shooter"
                        },
                        new
                        {
                            TypesId = "R",
                            Name = "RPG"
                        },
                        new
                        {
                            TypesId = "P",
                            Name = "Puzzle"
                        });
                });

            modelBuilder.Entity("Web_Server_Application_Final_Project.Models.Game", b =>
                {
                    b.HasOne("Web_Server_Application_Final_Project.Models.Types", "Type")
                        .WithMany()
                        .HasForeignKey("TypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Web_Server_Application_Final_Project.Models.Movie", b =>
                {
                    b.HasOne("Web_Server_Application_Final_Project.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });
#pragma warning restore 612, 618
        }
    }
}
